SELECT I.ANIMAL_ID AS 'ANIMAL_ID', I.ANIMAL_TYPE AS ANIMAL_TYPE, I.NAME AS 'NAME'
FROM animal_ins AS I
     LEFT JOIN animal_outs AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE LIKE 'Intact%' AND O.SEX_UPON_OUTCOME LIKE 'Neutered Male') OR (I.SEX_UPON_INTAKE LIKE 'Intact%' AND  O.SEX_UPON_OUTCOME LIKE 'Spayed Female')